# Uncomment the next line to define a global platform for your project


platform :ios, '8.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'VipVideo-iPhone' do

pod 'AXWebViewController'
pod 'HLAdditions'
pod 'FTPopOverMenu'
#pod 'TOWebViewController'
pod 'DZNEmptyDataSet'
pod 'Masonry'
pod 'CocoaHTTPServer'
pod 'Bugly'

end
