# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VipVideo-iPhone' do
  source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AXWebViewController'
  pod 'HLAdditions'
  pod 'FTPopOverMenu'
  #pod 'TOWebViewController'
  pod 'DZNEmptyDataSet'
  pod 'Masonry'
  pod 'CocoaHTTPServer'
  pod 'Bugly'
  pod 'SVProgressHUD'
end
